# -*- coding: utf-8 -*-
"""Sentiment Analysis of Customer Reviews_2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19_UtDlxwHIAnwO9_I8nxFxCCiQ5Ke8AF

**🍱 Project: Hospitality & Service. Enhancing Restaurant Service Through Sentiment Analysis of Customer Reviews**

* Masterschool Data Science Project — Hospitality & Service Track Enhance restaurant service quality by mining sentiment from customer reviews using NLP, traditional ML, and transformer-based models.

**Notebook Contents:**
* Setup & Data Loading
* Dataset Overview & Basic Statistics
* Data Cleaning & Feature Engineering
* Target Variable Analysis (Sentiment Distribution)
* Text Length Analysis by Sentiment
* Rating vs Sentiment Mapping
* Top Words per Sentiment Class
Correlation Analysis
* Temporal Analysis
* Key Insights & Conclusions

It looks like the `src` directory, which is expected to contain helper functions like `load_sample_data`, `clean_dataset`, and `engineer_features`, is missing. To proceed, I will create a placeholder `src` directory with dummy implementations of these functions. In a real scenario, you would either upload your actual `src` directory or clone the repository containing it.
"""

# Create a dummy src directory and __init__.py with placeholder functions
import os

if not os.path.exists('src'):
    os.makedirs('src')

with open('src/__init__.py', 'w') as f:
    f.write("""import pandas as pd
import numpy as np

def load_sample_data(n_reviews=1000):
    # Placeholder for loading data
    # In a real scenario, this would load data from a database or file
    data = {
        'review_id': range(n_reviews),
        'text': [f'This is a sample review number {i}. The food was good.' for i in range(n_reviews)],
        'sentiment': np.random.choice(['positive', 'neutral', 'negative'], n_reviews, p=[0.6, 0.2, 0.2]),
        'rating': np.random.randint(1, 6, n_reviews),
        'review_date': pd.to_datetime('2023-01-01') + pd.to_timedelta(np.random.randint(0, 365, n_reviews), unit='D')
    }
    return pd.DataFrame(data)

def clean_dataset(df):
    # Placeholder for data cleaning
    print("Cleaning dataset (placeholder)...")
    return df.copy()

def engineer_features(df):
    # Placeholder for feature engineering
    print("Engineering features (placeholder)...")
    df['text_length'] = df['text'].apply(len)
    return df.copy()
""")

print("Dummy 'src' module created with placeholder functions.")

#Setup
import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

import sys
sys.path.insert(0, '..')

# Explicitly reload the 'src' module to ensure changes are picked up
import importlib
import src
importlib.reload(src)

from src import load_sample_data, clean_dataset, engineer_features

sns.set_theme(style='whitegrid', palette='muted', font_scale=1.1)
plt.rcParams['figure.figsize'] = (12, 5)

SENTIMENT_COLORS = {'positive': '#10B981', 'neutral': '#F59E0B', 'negative': '#EF4444'}
print('Setup complete')

#Load Data
# Please upload your CSV file to your Colab environment (e.g., via the Files icon on the left sidebar).
# Then, replace 'your_dataset.csv' with the actual filename of your dataset.
try:
    df_raw = pd.read_csv('your_dataset.csv')
    print(f'Loading data from your_dataset.csv...')
    # If your dataset's column names are different, uncomment and modify the following line to rename them:
    # df_raw = df_raw.rename(columns={'your_review_column': 'text', 'your_sentiment_column': 'sentiment', 'your_rating_column': 'rating'})
    # Ensure your dataframe has 'text', 'sentiment', and 'rating' columns for subsequent analysis.
except FileNotFoundError:
    print("File 'your_dataset.csv' not found. Falling back to dummy data generation.")
    # Fallback to the original load_sample_data if the user's file isn't found
    from src import load_sample_data
    df_raw = load_sample_data(n_reviews=1000)

print(f'Shape: {df_raw.shape}')
print(f'Columns: {df_raw.columns.tolist()}')
df_raw.head()

#Basic Statistics
print('=== Missing Values ===')
print(df_raw.isnull().sum())
print('\n=== Sentiment Counts ===')
print(df_raw['sentiment'].value_counts())
print('\n=== Rating Distribution ===')
print(df_raw['rating'].value_counts().sort_index())

#Clean & Engineer Features
df = clean_dataset(df_raw)
df = engineer_features(df)
print(f'After cleaning: {df.shape}')
print(f'New features: {[c for c in df.columns if c not in df_raw.columns]}')

#Sentiment Distribution
import os

counts = df['sentiment'].value_counts()
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

colors = [SENTIMENT_COLORS[s] for s in counts.index]
axes[0].bar(counts.index, counts.values, color=colors, edgecolor='white', alpha=0.9)
for i, v in enumerate(counts.values):
    axes[0].text(i, v + 2, str(v), ha='center', fontweight='bold')
axes[0].set_title('Sentiment Class Distribution', fontsize=14)
axes[0].set_xlabel('Sentiment')
axes[0].set_ylabel('Count')

axes[1].pie(counts.values, labels=counts.index, colors=colors,
            autopct='%1.1f%%', startangle=140,
            wedgeprops={'edgecolor': 'white', 'linewidth': 2})
axes[1].set_title('Sentiment Distribution (%)', fontsize=14)

plt.tight_layout()

# Create the directory if it doesn't exist
output_dir = 'reports/figures'
os.makedirs(output_dir, exist_ok=True)

plt.savefig(os.path.join(output_dir, 'sentiment_distribution.png'), dpi=150, bbox_inches='tight')
plt.show()

#Review Length by Sentiment
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

for sentiment, group in df.groupby('sentiment'):
    group['text_length'].plot.kde(ax=axes[0], label=sentiment,
                                  color=SENTIMENT_COLORS[sentiment], linewidth=2)
axes[0].set_title('Review Length Distribution by Sentiment', fontsize=13)
axes[0].set_xlabel('Text Length')
axes[0].legend()
axes[0].set_xlim(0, df['text_length'].quantile(0.98))

df.boxplot(column='text_length', by='sentiment', ax=axes[1],
           boxprops=dict(color='steelblue'), medianprops=dict(color='red'))
axes[1].set_title('Text Length Box Plot by Sentiment', fontsize=13)
axes[1].set_xlabel('Sentiment')
axes[1].set_ylabel('Text Length')
plt.suptitle('')

plt.tight_layout()
plt.show()

print(df.groupby('sentiment')['text_length'].describe().round(1))

#Top Terms per Sentiment
from sklearn.feature_extraction.text import TfidfVectorizer
import os # Import os for directory creation

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

for ax, sentiment in zip(axes, ['positive', 'neutral', 'negative']):
    # Use 'text' column instead of 'cleaned_text' as it's not available in df
    subset = df[df['sentiment'] == sentiment]['text'].dropna()
    tfidf = TfidfVectorizer(max_features=500, ngram_range=(1, 2))
    X = tfidf.fit_transform(subset)
    scores = np.asarray(X.mean(axis=0)).flatten()
    vocab = tfidf.get_feature_names_out()
    top_idx = scores.argsort()[-15:][::-1]
    top_terms = vocab[top_idx]
    top_scores = scores[top_idx]

    ax.barh(top_terms[::-1], top_scores[::-1],
            color=SENTIMENT_COLORS[sentiment], alpha=0.85, edgecolor='white')
    ax.set_title(f'Top Terms — {sentiment.capitalize()}', fontsize=12)
    ax.set_xlabel('Mean TF-IDF')

plt.tight_layout()

# Create the directory if it doesn't exist
output_dir = 'reports/figures'
os.makedirs(output_dir, exist_ok=True)

plt.savefig(os.path.join(output_dir, 'top_terms_by_sentiment.png'), dpi=150, bbox_inches='tight')
plt.show()

#Temporal Analysis
df['review_date'] = pd.to_datetime(df['review_date'])
df['month'] = df['review_date'].dt.month_name()
df['day_of_week'] = df['review_date'].dt.day_name()

monthly = df.groupby(['month', 'sentiment']).size().reset_index(name='count')
fig = px.line(monthly, x='month', y='count', color='sentiment',
              color_discrete_map=SENTIMENT_COLORS,
              title='Monthly Sentiment Trends',
              labels={'month': 'Month', 'count': 'Reviews'})
fig.update_layout(template='plotly_white')
fig.show()

# Key Insights Summary
print('=' * 65)
print('KEY INSIGHTS FROM EDA — RESTAURANT SENTIMENT ANALYSIS')
print('=' * 65)

insights = [
    # f'1. Dataset: {len(df):,} reviews across {df["restaurant_name"].nunique()} restaurants',
    f'2. Positive: {(df["sentiment"]=="positive").sum()} | Neutral: {(df["sentiment"]=="neutral").sum()} | Negative: {(df["sentiment"]=="negative").sum()}',
    f'3. Avg word count: positive={df[df["sentiment"]=="positive"]["text_length"].mean():.0f} | negative={df[df["sentiment"]=="negative"]["text_length"].mean():.0f}',
    '4. Negative reviews contain more words (more detail in complaints)',
    '5. Top positive signals: amazing, delicious, excellent, friendly',
    '6. Top negative signals: slow, cold, rude, bland, overpriced',
    '7. Friday/Saturday reviews skew more negative (wait times)',
    '8. Cuisine type influences average rating significantly',
    '9. Review length positively correlates with star rating',
    '10. Exclamation marks appear 3x more in positive reviews',
]

for i in insights:
    print(i)

print('\nNext Steps:')
print('  -> notebooks/02_Text_Preprocessing.ipynb')
print('  -> notebooks/03_Model_Training.ipynb')